version: '3'
services:
  php-server:
    image: php:7.2-apache
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/site
      - ./php-config.conf:/etc/apache2/sites-enabled/000-default.conf
